version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"  # Jenkins UI 접속을 위한 포트
      - "50000:50000"  # Jenkins 에이전트가 연결될 포트
    volumes:
      - jenkins_home:/var/jenkins_home  # Jenkins 데이터 볼륨
      - /var/run/docker.sock:/var/run/docker.sock  # Docker 실행을 위한 소켓
    networks:
      - jenkins-net

volumes:
  jenkins_home:
    driver: local

networks:
  jenkins-net:
    driver: bridge